### PR TITLE
implement STRtree

### PR DESCRIPTION
**Pull request by maxfreu**
Happy querying! Unfortunately I can't make it work without the $ in cfunction, but maybe we can live like that.

### CODE REVIEW

**Comment by visr** [comment]
This is a nice contributions. thanks! I pushed a few commits. Could you review 6b1b2fa2318347f8d0a7087fa910e79742014d78 and see if you agree? Otherwise I think this is good to go. Maybe @evetion can comment on the callback interpolation?

The callback returned `pointer(Cvoid[])`, but returning `C_NULL` seems to work fine. Is the return value used for anything?

**Review by visr — APPROVED** [review]

**Comment by evetion** [comment]
I think the callback can be made much simpler. The Julia tree stores the items, so you don't need to pass them to libgeos. You can just insert an id that you can later use to create a view on items. If the passed item becomes static, say just an Int, I think we also don't need the @cfunction. Besides, this all should be much faster than inserting complex objects and later allocating them again.

**Comment by evetion** [comment]
Also, would it be possible to use GeoInterface here? Would just require LibGEOS.envelope to be defined on Any, which will try to use the GeoInterface bbox method and construct and Envelope from that?

**Comment by visr** [comment]
> You can just insert an id that you can later use to create a view on items.

This is essentially what happens now as well isn't it? `GEOSSTRtree_insert_r` expects pointers, and gets pointers to the items (not the underlying geometry.ptr but the wrapped geometry). GEOS won't and cannot do anything with the pointers, except pass them to the callback on a successful query.

> Besides, this all should be much faster than inserting complex objects and later allocating them again.

So only the pointers are inserted, and `unsafe_pointer_to_objref` won't copy or allocate, it is the same item as stored in the tree.

> Also, would it be possible to use GeoInterface here?

I think that's a good idea, but perhaps we should do that later, then this can get released before the breaking GeoInterface PRs are merged.

**Comment by maxfreu** [comment]
I couldn't have said it better.

I like the change allowing mixed types. But I'm not sure whether we can omit the calculation of the envelope before insertion. The [C wrapper docs](https://libgeos.org/doxygen/geos__c_8h.html#ad61927f5f808c166c7993a189c3b53d1) are not 100% clear and say `insert` needs "a GEOSGeometry whose envelope corresponds to the extent of 'item'. As of GEOS 3.9, this envelope will be copied into the tree and the caller may destroy g while the tree is still in use. Before GEOS 3.9, g must be retained until the tree is destroyed." The [C++ docs](https://libgeos.org/doxygen/classgeos_1_1index_1_1strtree_1_1STRtree.html#a9ca89d79af23375493acbc8286e7e3e4) are a bit more specific in so far as the function signature contains `const geom::Envelope * itemEnv` which makes me think I have to pass the pre-calculated envelope. But I haven't read the source and the tests pass, so maybe you're right. ... ok now I read a bit in the source and am pretty sure that at least at the insertion time the bounds are not calculated for us. But maybe that happens later?

**Comment by visr** [comment]
Ha ok thanks for checking. If we can't be sure then probably we should do it ourselves, because that's the safe thing to do. And calling envelope on an envelope will not be very costly (compared to a complex polygon).

**Pull request merged**
