### PR TITLE
add LibGEOSMakie

### PR DESCRIPTION
**Pull request by jw3126**
https://github.com/JuliaGeo/LibGEOS.jl/issues/142

### CODE REVIEW

**Review by yeesian — COMMENTED** [review]
Echoing https://github.com/JuliaGeo/LibGEOS.jl/issues/142#issuecomment-1304573840, this does feel like a lot to go from 
```julia
import GeoInterfaceMakie
GeoInterfaceMakie.@enable(LibGEOS.AbstractGeometry)
```
to
```julia
import LibGEOSMakie
```

If https://github.com/JuliaGeo/LibGEOS.jl/issues/142#issuecomment-1304575156 is a concern, can we ask the users to define their own
```julia
module LibGEOSMakie
import LibGEOS
import GeoInterfaceMakie
GeoInterfaceMakie.@enable(LibGEOS.AbstractGeometry)
end
```
?

**Comment by jw3126** [comment]
Yes I also don't like how much boilerplate is needed around this line of code to package it. From the user's POV I think 
```julia
using LibGEOSMakie
```
is much better than being asked to do some non-standard rituals like
```julia
import GeoInterfaceMakie
GeoInterfaceMakie.@enable(LibGEOS.AbstractGeometry)
```
Also if we ever need to update this, say (`@enable(More stuff)`) it is much easier to update a single package than every user's script.

If the user does her own 
```julia
module LibGEOSMakie
import LibGEOS
import GeoInterfaceMakie
GeoInterfaceMakie.@enable(LibGEOS.AbstractGeometry)
end
```
that is only useful if it can be accessed from multiple projects. Which means it needs to be packaged. Better package it once here than multiple times by users.

**Review by evetion — CHANGES_REQUESTED** [review]
First of all, thanks for the all work here, and in other PRs! Much appreciated.

With regards to this PR: I don't think adding new subpackages for plotting is a scalable approach, both in terms of boilerplate, as in the PRs needed.

If we think @enable_plots (whether from GeoInterfaceRecipes/GeoInterfaceMakie) is unusable from a user POV, we should try to improve/replace it. I don't know how that would look like (yet).

@rafaqz

**Comment by evetion** [comment]
> ```julia
> using LibGEOSMakie
> ```
> 
> is much better than being asked to do some non-standard rituals like
> 
> ```julia
> import GeoInterfaceMakie
> GeoInterfaceMakie.@enable(LibGEOS.AbstractGeometry)
> ```

I don't think one extra line is a ritual or exactly non-standard. For example, if you want to plot using Plots and PyPlot as backend, you have to do `pyplot()`.

> Also if we ever need to update this, say (`@enable(More stuff)`) it is much easier to update a single package than every user's script.
> 
> If the user does her own
> 
> ```julia
> module LibGEOSMakie
> import LibGEOS
> import GeoInterfaceMakie
> GeoInterfaceMakie.@enable(LibGEOS.AbstractGeometry)
> end
> ```
> 
> that is only useful if it can be accessed from multiple projects. Which means it needs to be packaged. Better package it once here than multiple times by users.

We are not in the business of updating user scripts, behavior of scripts should stay identical actually. `@enable(More stuff)` would imply a new feature of a script, so that's fine. We control GeoInterfaceMakie, so any bugs (or even adding `More stuff)` in `enable` can be done by us.

---

Now, I don't want to ignore your point that you would like "just to work" once you do `using GeoInterfaceRecipes/Makie`. I agree with that, but I'm not sure yet how to implement it yet.

Could we add wrappertypes in GeoInterface? Say the following for any custom `{T}` geometry that implements `geomtrait(T)=PolygonTrait()`? 
```julia
struct PolygonWrap{T}
	geom::{T}
end
```
Then `GeoInterfaceRecipes/Makie` could just provide recipes based on those types. Not sure about the performance.

**Comment by jw3126** [comment]
Thanks, @evetion ! I agree would be great to not have a better approach. My suspicion is however that we won't come up with something better any time soon, while I need this functionality now.

I see two options:
* We merge this PR and deprecate the package later, should we ever come up with a better mechanism
* I release this package under jw3126/LibGEOSMakie.jl so you don't need to maintain it at all.

What would you guys prefer?

**Comment by evetion** [comment]
> I release this package under jw3126/LibGEOSMakie.jl so you don't need to maintain it at all.

If you need this _now_, this is of course the best option. I'm on the fence for merging it and deprecating it later, maybe @rafaqz could chime in.

**Comment by rafaqz** [comment]
It seems pretty annoying for users to have to do anything at all to plot geometries. LibGEOS can't take a dependency on GeoInterfaceMakie.jl?

**Comment by visr** [comment]
> LibGEOS can't take a dependency on GeoInterfaceMakie.jl?

That was @jw3126's original proposal in #142. As mentioned there the biggest dependency it woul pull in would be GeometryBasics. That seemed a bit much to me but actually maybe it's fine, especially if it's going to shed weight with https://github.com/JuliaGeometry/GeometryBasics.jl/pull/173/files#diff-72ed386c2a0cd1d23c0968297e70023ed98c22490d146dd89fc91f48369bad4d, for instance dropping the StaticArrays dependency.

**Comment by visr** [comment]
@jw3126 I see you've set up https://github.com/jw3126/LibGEOSMakie.jl, which is pending registration. Shall we close this PR then for now? If we want we can move it in the subdirectory of this repo later.

Do you want to add a mention of LibGEOSMakie to the LibGEOS readme? And we can mention GeoInterfaceRecipes for Plots.jl users.

**Comment by rafaqz** [comment]
Is it really to large a dependency to just include here? MakieCore.jl only depends on Observables.jl. @visr are you thinking this still depends on Makie.jl?

**Comment by visr** [comment]
No I'm aware, that's why I posted https://github.com/JuliaGeo/LibGEOS.jl/pull/144#issuecomment-1311501323. It's mainly GeometryBasics. Though now that LibGEOSMakie exists, perhaps that is fine.

**Comment by jw3126** [comment]
> @jw3126 I see you've set up https://github.com/jw3126/LibGEOSMakie.jl, which is pending registration. Shall we close this PR then for now? If we want we can move it in the subdirectory of this repo later.

Feel free to close the PR, but maybe leave an issue open for making Makie + LibGEOS work out of the box?

> Do you want to add a mention of LibGEOSMakie to the LibGEOS readme? 

Great idea!

**Comment by visr** [comment]
I'll close this since https://github.com/jw3126/LibGEOSMakie.jl/ is registered and mentioned in the readme here: https://github.com/JuliaGeo/LibGEOS.jl#ecosystem

In the future we can also consider using extension packages that are part of julia 1.9 (to be released): https://pkgdocs.julialang.org/dev/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)

**Pull request closed without merging**
