### PR TITLE
Buffer can also return a MultiPolygon, not only a Polygon

### PR DESCRIPTION
**Pull request by evetion**
```
using LibGEOS

A = [[1.0, 1.0], [2.0, 2.0], [2.0, 0.0]]
buffersize = 0.5
mp = MultiPoint(A)
buffer = buffer(mp, buffersize)
```

`buffer` should be a MultiPolygon, but is cast as Polygon. 
Calling the internal function `coordinates` on this "Polygon" will lead to a crash.

### CODE REVIEW

**Comment by yeesian** [comment]
Thanks! Can you add it to the tests over at https://github.com/JuliaGeo/LibGEOS.jl/blob/699d52734700922220a55183cce344346792fb6e/test/test_geos_operations.jl as well?

**Comment by evetion** [comment]
I've added two tests that check the output type.

**Comment by yeesian** [comment]
Can you add the following patch: https://github.com/JuliaGeo/LibGEOS.jl/commit/9b8a61d1ef893ec1a4f4862597abbb96d2f8aac3 to this PR? Thanks!

**Comment by visr** [comment]
Added allowed failures to Travis & AppVeyor.
Note that this package is currently not being tested on v0.6, and it's failing for me on Win64 locally with what seems like #26, though that's not for this PR.

**Comment by yeesian** [comment]
Thanks all!

@visr should I release a new tag, or would you like some time to work out the bug on Win64 on julia v0.6 first?

**Comment by visr** [comment]
A new release now is fine, not sure when I can get to it. BTW, I don't know if you already did the same, but I enabled attobot for all JuliaGeo repos. Could not see the old setting. Let me know if that's not ok.

**Pull request merged**
