### PR TITLE
improve show

### PR DESCRIPTION
**Pull request by jw3126**
```julia
julia> Point(1,2,3) # before
Point(Ptr{Nothing} @0x000000000511a220, LibGEOS.GEOSContext(Ptr{Nothing} @0x0000000001e06780))

julia> Point(1,2,3) # after
readgeom("POINT Z (1 2 3)")::Point

julia> Polygon([[[1.0,2], [3.0,4], [5.0,6], [1.0,2]]]) # before
Polygon(Ptr{Nothing} @0x0000000002add7e0, LibGEOS.GEOSContext(Ptr{Nothing} @0x0000000001e06780))

julia> Polygon([[[1.0,2], [3.0,4], [5.0,6], [1.0,2]]]) # after
readgeom("POLYGON ((1 2, 3 4, 5 6, 1 2))")::Polygon
```

### CODE REVIEW

**Comment by evetion** [comment]
Thanks, this is an improvement! 

Could you add the use of the compact keyword? As in https://github.com/yeesian/ArchGDAL.jl/blob/master/src/base/display.jl#L254. This will help with performance and displaying in tables.

**Comment by visr** [comment]
Indeed a great improvement. I assume that you went for `readgeom("POINT Z (1 2 3)")::Point` to make it easy to recreate the geometry. It does feel a bit verbose though. What about just showing the WKT, `POINT Z (1 2 3)` It looks like shapely does this as well: https://shapely.readthedocs.io/en/stable/manual.html#Point.

And (this could be a separate PR), but it would be cool to support other mime types, like `application/geo+json`, which jupyter supports: https://docs.jupyter.org/en/latest/reference/mimetype.html.

**Comment by jw3126** [comment]
> Indeed a great improvement. I assume that you went for readgeom("POINT Z (1 2 3)")::Point to make it easy to recreate the geometry. It does feel a bit verbose though. What about just showing the WKT, POINT Z (1 2 3) It looks like shapely does this as well: https://shapely.readthedocs.io/en/stable/manual.html#Point.

Yes I had the same ideas, it is a tradeoff and I had a slight preference for convenient recreation, but I can change it if you feel strongly about this.

**Comment by jw3126** [comment]
@evetion done
@visr I changed according to your suggestion

**Comment by jw3126** [comment]
```julia
julia> p = Polygon([[[0.0, 0.0] for _ in 1:10000]]); show(IOContext(stdout, :compact=>true),p)
POLYGON ((0 0, 0 0, 0 0, 0 0, 0 0, 0 0,  ... 0 0, 0 0, 0 0, 0 0, 0 0, 0 0))
```

**Comment by evetion** [comment]
I would opt for never calling `writegeom`/showing WKT at all when :compact is set to true, as in the ArchGDAL code (it only displays the geometry type then).

**Review by visr — APPROVED** [review]
Looks good to me! I like the 3 dots in the compact show to make it clear that it's an instance and not just the type (`Polygon(...)`). @evetion do you agree?

**Pull request merged**
