### PR TITLE
add getPrecision and setPrecision

### PR DESCRIPTION
**Pull request by jaakkor2**
Fixes https://github.com/JuliaGeo/LibGEOS.jl/issues/64

### CODE REVIEW

**Comment by visr** [comment]
Thanks for this, looks great! Would you mind adding some docstrings for these two functions as well? I know they are lacking for many others as well, but it would be nice to make progess on getting all exported functions documented.

Do you think it makes sense to make `setPrecision`'s `flag` a keyword argument instead, with I guess default 0? Would make it easier to use without having to figure out what `flag` means/should be.

**Comment by jaakkor2** [comment]
I’ll add doc strings next week. Putting `flag` as a keyword sounds more convenient.

Rethinking `setPrecision`, I would prefer I could write

```julia
geom1_ = readgeom("LINESTRING(2 10, 4 30)")
g = setPrecision(geom1_, 2.0)
```
instead of
```julia
geom1_ = readgeom("LINESTRING(2 10, 4 30)")
g = LineString(setPrecision(geom1_, 2.0))
```

**Comment by visr** [comment]
Oh yeah good point. It would be much nicer if we get the original types back. I guess you could just modify

```julia
@eval setPrecision(obj::$geom, grid::Real, flags::Int, context::GEOSContext = _context) = setPrecision(obj.ptr, grid::Real, flags::Int, context)
to
@eval setPrecision(obj::$geom, grid::Real, flags::Int, context::GEOSContext = _context) = $geom(setPrecision(obj.ptr, grid::Real, flags::Int, context))
```

**Comment by jaakkor2** [comment]
From my side, good to go.

**Pull request merged**
