### PR TITLE
add Makie extension

### PR DESCRIPTION
**Pull request by rafaqz**

### CODE REVIEW

**Comment by rafaqz** [comment]
1.6 strikes again... should we:
1. Just use 1.9 and up now, 1.10 is already out
2. Don't test Makie plots below 1.9

**Review by jw3126 — APPROVED** [review]
LGTM should we bump the version?

**Comment by jaakkor2** [comment]
Makie should not be listed in the `[deps]`-section https://github.com/JuliaGeo/LibGEOS.jl/blob/makie/Project.toml#L13 to keep dependencies light.

**Comment by rafaqz** [comment]
Oh nice catch thats a mistake

**Pull request merged**
