### PR TITLE
use GEOS_jll GEOS 3.8.0 artifacts

### PR DESCRIPTION
**Pull request by visr**
https://github.com/libgeos/geos/blob/3.8/NEWS

This will require at least julia 1.3. Testing to see if it works. If it does, it may be tempting to drop support for older versions, see https://github.com/JuliaGeo/GDALBuilder/issues/11#issuecomment-544858695.

Some tests with pointOnSurface had to be updated. This is expected since it can return any point on the surface. Other than that some GeometryCollections are now ordered differently, and the unary union of an empty point remains an empty point.

~~The second commit seems like getDimensions is not working properly, will need to investigate.~~ (edit: it was calling the wrong method)

- [x] wait for julia 1.3 release and set in in the Project.toml compat section
- [x] rerun wrap_geos.jl

### CODE REVIEW

**Comment by jaakkor2** [comment]
I am testing with Julia v"1.3.0-rc5.1".  Looks good, unary union of lines seems to be 40% faster in my use case. Few notes

1. `LibGEOS.GEOS_VERSION` returns `"3.7.2"`, looks like
https://github.com/JuliaGeo/LibGEOS.jl/blob/artifact/src/geos_common.jl
was not updated.

2. My `.julia\artifacts\899bb0e10d4accc34dff74b1c82ffbfe56dc8b23\lib` contains 79 MB of `.a` and .`la` that somewhat look unnecessary to me.  Are they needed in some use case?  On the positive side, looks like the `downloads`-subfolder with a tar.gz-file is gone.

**Comment by visr** [comment]
Thanks for having a look! Great to see the performance improvement.

You're right, I did not yet rerun the wrapper script, which needs to be done as well, as noted here: https://github.com/JuliaGeo/LibGEOS.jl/blob/1b2f2d4e0210193d29bb99f397e51a051a3df8ea/gen/wrap_geos.jl#L7-L11. I added it as a TODO on the top post.

I think the static libraries are not needed, and should probably be turned off to save space. This was done for GDAL in https://github.com/JuliaGeo/GDALBuilder/commit/5125074660448904a000fb7272a2ef8656224449. I'm not sure if the same command works for GEOS? Otherwise it would be a welcome contribution to https://github.com/JuliaPackaging/Yggdrasil/tree/master/G/GEOS.

**Comment by visr** [comment]
@jaakkor2 I think this is good to go from my side. It is picking up the new artifact, which only weighs 10MB unpacked, compared to 150MB before. Thanks for helping to reduce the size!

@yeesian and others, OK to require at least julia 1.3 for this package on master? I created a `release-0.5` branch for if we still want to do bugfix releases on versions that support julia 1.0 to 1.2.

**Comment by yeesian** [comment]
> OK to require at least julia 1.3 for this package on master?

Okay

**Pull request merged**
