### PR TITLE
Implement GeoInterface isempty, x, and y.

### PR DESCRIPTION
**Pull request by evetion**
As triggered by https://github.com/asinghvi17/GeometryOps.jl/pull/33

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks. I guess we need a method for plotting onlyp missing values in GeoInterfaceMakie.jl?

**Comment by evetion** [comment]
> Thanks. I guess we need a method for plotting only missing values in GeoInterfaceMakie.jl?

Not sure, I didn't follow that discussion. I just saw `isempty` return false, which was clearly incorrect. 😅

**Comment by rafaqz** [comment]
Iean the test failures

**Review by rafaqz — APPROVED** [review]
LGTM

**Pull request merged**
