### PR TITLE
Move from FactCheck to Base.Test

### PR DESCRIPTION
**Pull request by visr**
On top of #43

### CODE REVIEW

**Comment by visr** [comment]
Failing on Travis Linux with
```
signal (11): Segmentation fault
while loading /home/travis/.julia/v0.6/LibGEOS/test/test_invalid_geometry.jl, in expression starting on line 1
unknown function (ip: 0xffffffffffffffff)
```

This test is using the deprecated `GEOSGeomFromWKT`, see #21, so possibly it is using a binary where they are removed? Don't see anything here though: https://trac.osgeo.org/geos/browser/git/NEWS

**Comment by yeesian** [comment]
Yeah, I'm not sure about this either.

**Comment by yeesian** [comment]
I'd be okay with leaving out the test for now, and leaving a note to revisit it when we address #21, what do you think?

**Comment by visr** [comment]
Yes agree, just commented it out, let's see if CI is happy now.

**Comment by yeesian** [comment]
Thanks!

**Pull request merged**
