### PR TITLE
Add gitignore for build files/dirs

### PR DESCRIPTION
**Pull request by OmriRoames**
* these files/dirs cause the packaging to crush

### CODE REVIEW

**Comment by visr** [comment]
It'd be good to have a `.gitignore`. However I don't understand how not having one can cause it to crash. Could you elaborate, or show the error message? What system are you on?

**Comment by OmriRoames** [comment]
I was trying to package my locally (Linux mint) my stuff that uses LibGEOS in order to run it on a cluster. The source code is downloaded, and GEOS is build. This is all good. The problem comes from the coupling to DeclarativePackages.jl: 
```
ERROR: LoadError: SubString{ASCIIString}["?? deps/builds/","?? deps/downloads/","?? deps/src/","?? deps/usr/"] -- Cannot create a jdp declaration from the currently installed packages as '/home/omri/.julia/declarative/lz8uzmbdIGia1Vtd3Ub1aw5Lde0bcIq6/v0.4/LibGEOS/LibGEOS' has local changes.
Please commit these changes, then run 'jdp' again.
 in error at ./error.jl:21
 in generatespecs at /home/omri/.julia/v0.4/DeclarativePackages/src/DeclarativePackages.jl:77
 in exportDECLARE at /home/omri/.julia/v0.4/DeclarativePackages/src/DeclarativePackages.jl:22
 in finish at /home/omri/.julia/v0.4/DeclarativePackages/src/installpackages.jl:228
 in installpackages at /home/omri/.julia/v0.4/DeclarativePackages/src/installpackages.jl:14
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/omri/.julia/v0.4/DeclarativePackages/src/installpackages.jl, in expression starting on line 253
```
The error arise from the presence of the untracked files/dirs from the build which is picked up as "dirty" by `git status -s`. Ignoring the files and directories created by the build solve this issue.

**Comment by yeesian** [comment]
Thanks for clarifying! This is not particularly common practice, but [SCS does it](https://github.com/JuliaOpt/SCS.jl/blob/master/deps/.gitignore), so I'm okay with merging this PR if @visr gives it the green light.

**Comment by visr** [comment]
Sure, go ahead. Perhaps also good to already add the .gitignore lines that
PkgDev.generate() automatically adds these days?
```
*.jl.cov
*.jl.*.cov
*.jl.mem
```

**Comment by OmriRoames** [comment]
Sure, I'll add it as well

**Comment by yeesian** [comment]
I've added it, no worries!

**Comment by yeesian** [comment]
I've squashed and rebased this branch @OmriRoames, you should checkout master after it gets merged.

**Comment by OmriRoames** [comment]
Did you tag it?

**Comment by yeesian** [comment]
Nope! Letting you give it a shot based on https://github.com/JuliaGeo/GeoInterface.jl/issues/5#issuecomment-215279355

**Comment by OmriRoames** [comment]
I"m have some trouble with updating the metadata: We have our own copy of
the Metadata that includes some privet repositories which is obviously the
wrong thing for public updates, and I can't figure out how to have a copy
of the public metadata which is what I really want to update. I tried to
have a second remote in the gitconfig of the METADATA.jl but I don't know
how to branch off from the public master. any advise?

On 6 May 2016 at 08:46, Yeesian Ng <notifications@github.com> wrote:

> Nope! Letting you give it a shot based on JuliaGeo/GeoInterface.jl#5
> (comment)
> <https://github.com/JuliaGeo/GeoInterface.jl/issues/5#issuecomment-215279355>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaGeo/LibGEOS.jl/pull/15#issuecomment-217302082>
>



-- 

*Dr. Omri Bahat Treidel* | Software & Algorithm engineer | Fugro ROAMES Pty
Ltd
Level 1 | 53 Brandl Street | Eight Mile Plains, QLD, 4113, Australia | ( | P.O.
Box 10, Sunnybank Qld 4109, Australia, Australia)
T: 1800 ROAMES (+61 1800 762 637) | E: omri.treidel@roames.com.au | linkedin
<http://au.linkedin.com/pub/omri-bahat-treidel/28/a84/116> |
www.fugroroames.com.au

Observe | Model | Simulate

**Pull request merged**
