### PR TITLE
fix tests always passing

### PR DESCRIPTION
**Pull request by visr**
Now it calls `FactCheck.exitstatus()` to get the right exit code for CI.
Also wrapping the test code blocks to get logging of which tests fail.

### CODE REVIEW

**Comment by visr** [comment]
Since Base.Test is now much improved FactCheck is not really needed anymore, I guess that is also the reason it lives in JuliaArchive nowadays. Is there any reason to stick with FactCheck?

**Comment by yeesian** [comment]
I've heard that Base.Test can be quite slow though, not sure if that has changed? But no, we don't have to stick with FactCheck.

**Comment by yeesian** [comment]
LGTM. Feel free to merge if there are no more pending changes.

**Comment by yeesian** [comment]
Maybe we should also start activating coveralls/codecov on this repo, in a separate PR, given that the issues have been surfacing portions of the codebase that were untested.

**Comment by visr** [comment]
Actually I forgot the part that is supposed to make all tests go red, just pushed that.

I see 14 existing test failures. Will fix those as well in this PR if simple enough.

**Comment by visr** [comment]
I fixed 4 tests that were clear/easy. With the others I'm not sure if the expected output or the functions need to be changed, if you have time could you check, @yeesian? I'll merge this now.

**Comment by yeesian** [comment]
I'll look into it; please don't merge yet.

**Comment by yeesian** [comment]
It was all just test fixes, and didn't surface any further issues with the codebase. I'm okay with merging on green.

**Comment by visr** [comment]
Great, thanks, was hoping as much. Good to have a green we can believe in :)

**Pull request merged**
