### PR TITLE
Update to latest version available on the buildserver

### PR DESCRIPTION
**Pull request by evetion**
See https://build.opensuse.org/project/show/home:yeesian

### CODE REVIEW

**Comment by evetion** [comment]
Some builds are failing because of download errors. Weird, because the url in all the error messages seems to work for me.

**Comment by visr** [comment]
WinRPM is now using openSUSE_Leap_42.2, would perhaps be good to start building on that and change the repository in `build.jl` to 
`http://download.opensuse.org/repositories/home:yeesian/openSUSE_Leap_42.2`

Travis download error I also don't understand, seems unrelated to this PR.

**Comment by yeesian** [comment]
Strangely enough, all the builds are passing under my personal account, but not under the JuliaGeo account on AppVeyor:

image

**Comment by visr** [comment]
image
Trying to get the build to run, I added these repositories such that it can find the dependencies.

**Comment by yeesian** [comment]
> Trying to get the build to run, I added these repositories such that it can find the dependencies.

Thanks! I was unsuccessfully trying to figure out how to do the same for some time.

**Comment by visr** [comment]
Even though the GEOS OBS builds are now successful, there is not yet a `openSUSE_Leap_42.2` folder at the [download page](http://download.opensuse.org/repositories/home:/yeesian/).

Maybe needs some time...

**Pull request merged**
